market/core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('owner/', views.owner, name='owner'),
]

market/item/urls.py
from django.urls import path
from . import views
app_name = 'item' # namespace for item app

urlpatterns = [
    path('detail/<int:id>/', views.detail, name='detail'),
    path('create-item/', views.createItem, name='create-item'),
    path('edit-item/<int:id>', views.editItem, name='edit-item'),
    path('delete-item/<int:id>/', views.deleteItem, name='delete-item'),
    path('women/', views.women, name='women'),
    path('men/', views.men, name='men'),
    path('kids/', views.kids, name='kids'),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import *
from item.views import *

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/core/models.py
from django.db import models

market/item/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False, default="text")
    price = models.FloatField(null=False)
    image = models.ImageField(upload_to='item_images', null=False)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

market/shoe/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images')
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

market/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        # email, pass, enter pass again
        fields = ('email', 'password1', 'password2')

market/item/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        exclude = ['is_sold']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

market/core/views.py
from django.shortcuts import render
from item.models import Item 

# render homepage
def home(request):
    items = Item.objects.filter(is_sold=False)[0:3]
    
    return render(request, 'core/home.html', {
        'items': items
    })

# render contact page
def about(request):
    return render(request, 'core/about.html')

# render owner page
def owner(request):
    return render(request, 'core/owner.html')

market/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item
from item.forms import ItemForm
from django.contrib import messages

# renders and saves form to create a new listing
def createItem(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid(): 
            new_item = form.save()
            messages.success(request, 'Item listed successfully!')
            return redirect('item:detail', id=new_item.id)
    else:
        form = ItemForm()

    return render(request, 'item/create-item.html', {
        'form': form
    })

# update an existing listing
def editItem(request, id):
    item = get_object_or_404(Item, pk=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        msg = messages.success(request, "Listing Updated Successfully")
        form.save()
        return redirect('item:detail', id=id)
    
    return render(request, 'item/edit-item.html', {
        'form': form,
        'item': item,
    })

def deleteItem(request, id):
    item = get_object_or_404(Item, pk=id)
    item.delete()
    messages.success(request, 'Item successfully deleted!')

    return redirect('core:home')

# lists details of an item
def detail(request, id):
    item = get_object_or_404(Item, pk=id)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=id)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

def women(request):
    category_items = Item.objects.filter(category__name="Women", is_sold=False)
    
    query = request.GET.get('query', '')
    if query:
        category_items = category_items.filter(Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/category-items.html', {
         'category_items': category_items,
         'category': 'Women',
         'query': query,
    })

def men(request):
    category_items = Item.objects.filter(category__name="Men", is_sold=False)
    
    query = request.GET.get('query', '')
    if query:
        category_items = category_items.filter(Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/category-items.html', {
         'category_items': category_items,
         'category': 'Men',
         'query': query,
    })


def kids(request):
    category_items = Item.objects.filter(category__name="Kids", is_sold=False)
    
    query = request.GET.get('query', '')
    if query:
        category_items = category_items.filter(Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/category-items.html', {
         'category_items': category_items,
         'category': 'Kids',
         'query': query,
    })

market/core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Create Item{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <!-- Image Column -->
        <div class="col-md-6">
          <div style="width: 550px; height: 600px; overflow: hidden;">
            <img src="{% static 'about.jpg' %}" class="img-fluid" style="width: 100%; height: auto;">
          </div>
        </div>
        <!-- Details Column -->
        <div class="col-md-6">
            <div class="bg-light p-3 rounded">
              <h2>About Us</h2>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Blanditiis officia unde fuga aut. Ipsum, repellendus accusantium? Illo modi nulla veritatis neque quidem delectus? Nobis cumque sint minima aspernatur itaque hic.</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

market/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Step</title>
    <link rel="icon" href="{% static 'icon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <style type="text/css">
      .dropdown:hover .dropdown-menu {
        display: block;
      }
      .navbar {
        border-bottom: 1px solid #d4d4d4;
       }
    </style>  
  </head>
  <body> 

    <!-- NavBar -->
    <nav class="navbar navbar-expand-sm navbar-light">
      <div class="container">
          <a href="{% url 'core:home' %}" class="navbar-brand">Step</a>
          <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="nav" aria-label="Expand Navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="nav">
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a href="{% url 'core:home' %}" class="nav-link" aria-current="Home">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                          Products
                      </a>
                      <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'item:women' %}">Women</a>
                          <a class="dropdown-item" href="{% url 'item:men' %}">Men</a>
                          <a class="dropdown-item" href="{% url 'item:kids' %}">Kids</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">On Sale</a>
                      </div>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'core:about' %}" class="nav-link">About</a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'core:about' %}" class="nav-link">Account</a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'core:owner' %}" class="nav-link">Owner</a>
                  </li>
              </ul>
          </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="m-3">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-black text-white pt-5 pb-4">
      <div class="container text-center text-md-left">
          <div class="row text-center text-md-left">
        
            <!-- Step Section -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h5 class="text-uppercase mb-4 font-weight-bold">Step</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, praesentium.</p>
              <img src="{% static 'icon.png' %}" width="80" height="80" alt="Step Logo">
              <p style="color: grey; font-size: 15px"> STEP © 2023 </p>
            </div>

            <!-- Products Section -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h5 class="text-uppercase mb-4 font-weight-bold text-white">Products</h5>
              <p><a href="{% url 'item:women' %}" class="text-white">Women</a></p>
              <p><a href="{% url 'item:men' %}" class="text-white">Men</a></p>
              <p><a href="{% url 'item:kids' %}" class="text-white">Kids</a></p>
            </div>

            <!-- Useful Links Section -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h5 class="text-uppercase mb-4 font-weight-bold text-white">Useful Links</h5>
              <p><a href="#" class="text-white">Your Account</a></p>
              <p><a href="#" class="text-white">Your Orders</a></p>
              <p><a href="#" class="text-white">Shipping Rates</a></p>
              <p><a href="#" class="text-white">Returns</a></p>
            </div>
            <!-- Contact Section -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-white">Contact</h5>
                <p><i class="fas fa-home mr-3"></i> Dallas, TX</p>
                <p><i class="fas fa-envelope mr-3"></i> step@gmail.com</p>
                <p><i class="fas fa-phone mr-3"></i> (888) 888-8888</p>

                <!-- Spacer to push the icons to the bottom -->
                <div class="col-md-5 col-lg-4 flex-grow-1"></div>

                <!-- Social Media Icons Section -->
                  <ul class="list-unstyled list-inline mb-0">
                      <li class="list-inline-item">
                          <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-instagram"></i></a>
                      </li>
                      <li class="list-inline-item">
                          <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-twitter"></i></a>
                      </li>
                      <li class="list-inline-item">
                          <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-tiktok"></i></a>
                      </li>
                  </ul>
            </div>
        </div>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

market/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

{% for msg in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">      
  {{ msg }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
 
  <div class="container">
    <h3>Shop new arrivals</h3>
    <div class="row">
      {% for item in items %}
        <div class="col-sm {% if forloop.counter|divisibleby:3 %}mb-4{% endif %}">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'item:detail' item.id %}"> 
                    <img class="card-img-top" 
                      width="286"
                      height="342"
                      src="{{ item.image.url }}"
                      alt="Card image cap">
                </a>
              <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">${{ item.price }}</p>    
              </div>
            </div>
        </div>
      {% endfor %}
    </div>
  </div>     
{% endblock %}

market/core/templates/core/owner.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h2>Owner's Dashboard</h2>
            <a class="btn btn-outline-dark" href="{% url 'item:create-item' %}">Create Item</a>
        </div>
    </div>
</div>
{% endblock %}

market/item/templates/item/category-items.html
{% extends 'core/base.html' %}

{% block title %}Shop {{category}}{% endblock %}

{% block content %}

  <div class="container">
      <!-- Search Bar Row -->
    <div class="row">
      <div class="col-md">
        <form method="get" action="{% url 'item:women' %}">
          <div class="input-group input-group-md">
            <input type="text" name="query" class="form-control" value="{{ query }}" placeholder="Search by color, title, or brand...">
            <button type="submit" class="btn btn-primary">Search</button>
          </div>
        </form>
      </div>
    </div>
    <div style="margin-bottom: 1rem"></div>

    <!-- Cards Row -->
    <div class="row">
      {% for item in category_items %}
        <div class="col-md {% if forloop.counter|divisibleby:3 %}mb-4{% endif %}">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'item:detail' item.id %}"> 
                    <img class="card-img-top" 
                      width="286"
                      height="342"
                      src="{{ item.image.url }}"
                      alt="Card image cap">
                </a>
              <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">${{ item.price }}</p>    
              </div>
            </div>
        </div>
      {% endfor %}
    </div>
  </div>     
{% endblock %}

market/item/templates/item/create-item.html
{% extends 'core/base.html' %}

{% block title %}Create Item{% endblock %}

{% block content %}

  {% for msg in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">      
    {{ msg }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

market/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}Create Item{% endblock %}

{% block content %}

{% for msg in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">      
  {{ msg }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}

<div class="container">
    <div class="row">
        <!-- Image Column -->
        <div class="col-md-6">
          <div style="width: 550px; height: 600px; overflow: hidden;">
            <img src="{{ item.image.url }}" class="img-fluid" style="width: 100%; height: auto;">
          </div>
        </div>
        <!-- Details Column -->
        <div class="col-md-6">
            <div class="bg-light p-3 rounded">
                <h1>{{ item.title }}</h1>
                <p><strong>Price:</strong> ${{ item.price }}</p>
                <p><strong>Description:</strong><br>{{ item.description}}</p>
                <select class="form-select" aria-label="Default select example">
                  <option selected>Select Size</option>
                  <option value="1">5</option>
                  <option value="1">5.5</option>
                  <option value="1">6</option>
                  <option value="1">6.5</option>
                  <option value="1">7</option>
                  <option value="1">7.5</option>
                  <option value="1">8</option>
                </select>
                <div style="margin-top: 1rem;"></div>
                <button class="btn btn-dark">Add to Cart</button>
                <a href="{% url 'item:edit-item' item.id %}" class="btn btn-dark">Edit Listing</a>
                <a href="{% url 'item:delete-item' item.id %}" onclick="return confirmDelete()" 
                   class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

<div class="container">
  <div style="margin-top: 1rem;"></div>
    <h2>You may also like</h2>
    <div class="row">
      {% for item in related_items %}
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'item:detail' item.id %}"> 
                    <img class="card-img-top" 
                      width="286"
                      height="342"
                      src="{{ item.image.url }}"
                      alt="Card image cap">
                </a>
              <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">${{ item.price }}</p>    
              </div>
            </div>
        </div>
      {% endfor %}
    </div>
  </div>     

  <script>
    function confirmDelete() {
        return confirm('Are you sure you want to delete this listing?');
    }
  </script>

{% endblock %}

market/item/templates/item/edit-item.html
{% extends 'core/base.html' %}

{% block title %}Create Item{% endblock %}

{% block content %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Update">
  </form>
{% endblock %}